# ============================================================
# REPRODUCIBILITY CHECKS
# ============================================================
#
# Purpose
# -------
# Compare the outputs generated by the analytical workflow
# against a fixed set of previously verified reference values.
#
# These checks are regression/reproducibility controls.
# They are NOT an external validation of the Bayesian model,
# UREH classification, or clustering solution.
#
# Expected values:
#   checks/expected_results.csv
#
# This script should be run AFTER R/13_build_spatial_results.R.
#
# ============================================================


# ------------------------------------------------------------
# 0. Configuration
# ------------------------------------------------------------

source("R/00_config.R")


if (!requireNamespace(
  "sf",
  quietly = TRUE
)) {
  stop(
    "Package 'sf' is required for reproducibility checks."
  )
}


# ------------------------------------------------------------
# 1. Paths
# ------------------------------------------------------------

expected_file <- here::here(
  "checks",
  "expected_results.csv"
)


sensitivity_file <- here::here(
  "results",
  "tables",
  "sensitivity_by_unit.csv"
)


TM_file <- here::here(
  "results",
  "tables",
  "tm_diagnostic_by_unit.csv"
)


clustering_file <- here::here(
  "results",
  "tables",
  "clustering_C1_C2_assignments.csv"
)


spatial_gpkg <- here::here(
  "results",
  "spatial",
  "ureh_results.gpkg"
)


required_files <- c(
  expected_file,
  sensitivity_file,
  TM_file,
  clustering_file,
  spatial_gpkg
)


missing_files <- required_files[
  !file.exists(
    required_files
  )
]


if (
  length(
    missing_files
  ) > 0L
) {
  stop(
    "Required reproducibility files not found:\n",
    paste(
      missing_files,
      collapse = "\n"
    )
  )
}


# ------------------------------------------------------------
# 2. Read expected values
# ------------------------------------------------------------

expected <- read.csv(
  expected_file,
  stringsAsFactors = FALSE,
  check.names = FALSE
)


required_expected_fields <- c(
  "block",
  "metric",
  "expected",
  "tolerance"
)


missing_expected_fields <- setdiff(
  required_expected_fields,
  names(
    expected
  )
)


if (
  length(
    missing_expected_fields
  ) > 0L
) {
  stop(
    "expected_results.csv is missing fields: ",
    paste(
      missing_expected_fields,
      collapse = ", "
    )
  )
}


if (
  nrow(
    expected
  ) != 44L
) {
  stop(
    "Expected 44 reference controls; found ",
    nrow(
      expected
    ),
    "."
  )
}


if (
  anyDuplicated(
    expected[
      ,
      c(
        "block",
        "metric"
      )
    ]
  )
) {
  stop(
    "Duplicated block-metric combinations in expected_results.csv."
  )
}


if (
  anyNA(
    expected$expected
  ) ||
  anyNA(
    expected$tolerance
  )
) {
  stop(
    "Missing expected values or tolerances."
  )
}


# ------------------------------------------------------------
# 3. Helper functions
# ------------------------------------------------------------

as_bool <- function(
    x
) {
  
  if (
    is.logical(
      x
    )
  ) {
    return(
      x
    )
  }
  
  
  x_character <- toupper(
    trimws(
      as.character(
        x
      )
    )
  )
  
  
  output <- rep(
    NA,
    length(
      x_character
    )
  )
  
  
  output[
    x_character %in%
      c(
        "TRUE",
        "T",
        "1"
      )
  ] <- TRUE
  
  
  output[
    x_character %in%
      c(
        "FALSE",
        "F",
        "0"
      )
  ] <- FALSE
  
  
  if (
    anyNA(
      output
    )
  ) {
    stop(
      "Could not safely convert a logical field."
    )
  }
  
  
  output
}


# ------------------------------------------------------------
# Adjusted Rand Index
# ------------------------------------------------------------
#
# Implemented directly so the reproducibility check does not
# depend on an additional package.
#
# ------------------------------------------------------------

adjusted_rand_index <- function(
    x,
    y
) {
  
  if (
    length(x) !=
    length(y)
  ) {
    stop(
      "ARI vectors have different lengths."
    )
  }
  
  
  contingency <- table(
    x,
    y
  )
  
  
  choose2 <- function(
    z
  ) {
    
    z *
      (
        z - 1
      ) /
      2
  }
  
  
  sum_cells <- sum(
    choose2(
      contingency
    )
  )
  
  
  row_sums <- rowSums(
    contingency
  )
  
  
  col_sums <- colSums(
    contingency
  )
  
  
  sum_rows <- sum(
    choose2(
      row_sums
    )
  )
  
  
  sum_cols <- sum(
    choose2(
      col_sums
    )
  )
  
  
  n <- sum(
    contingency
  )
  
  
  total_pairs <- choose2(
    n
  )
  
  
  expected_index <-
    (
      sum_rows *
        sum_cols
    ) /
    total_pairs
  
  
  max_index <-
    0.5 *
    (
      sum_rows +
        sum_cols
    )
  
  
  denominator <-
    max_index -
    expected_index
  
  
  if (
    abs(
      denominator
    ) <
    .Machine$double.eps
  ) {
    
    return(
      1
    )
  }
  
  
  (
    sum_cells -
      expected_index
  ) /
    denominator
}

# ------------------------------------------------------------
# Helper to add one observed control
# ------------------------------------------------------------

actual_rows <- list()


add_control <- function(
    block,
    metric,
    actual
) {
  
  if (
    length(actual) != 1L
  ) {
    stop(
      "Control ",
      block,
      "/",
      metric,
      " did not produce a scalar value."
    )
  }
  
  
  if (
    is.na(actual) ||
    !is.finite(actual)
  ) {
    stop(
      "Control ",
      block,
      "/",
      metric,
      " produced an invalid value."
    )
  }
  
  
  actual_rows[[length(actual_rows) + 1L]] <<- data.frame(
    
    block = block,
    
    metric = metric,
    
    actual = as.numeric(actual),
    
    stringsAsFactors = FALSE
  )
  
  
  invisible(NULL)
}
# ============================================================
# 4. READ FINAL SPATIAL PRODUCTS
# ============================================================

available_layers <- sf::st_layers(
  spatial_gpkg
)$name


required_layers <- c(
  "m0_ureh",
  "sensitivity",
  "tm_diagnostic",
  "clustering_c1_c2"
)


missing_layers <- setdiff(
  required_layers,
  available_layers
)


if (
  length(
    missing_layers
  ) > 0L
) {
  stop(
    "Spatial GeoPackage is missing layers: ",
    paste(
      missing_layers,
      collapse = ", "
    )
  )
}


M0_sf <- sf::st_read(
  spatial_gpkg,
  layer = "m0_ureh",
  quiet = TRUE
)


sensitivity_sf <- sf::st_read(
  spatial_gpkg,
  layer = "sensitivity",
  quiet = TRUE
)


TM_sf <- sf::st_read(
  spatial_gpkg,
  layer = "tm_diagnostic",
  quiet = TRUE
)


clustering_sf <- sf::st_read(
  spatial_gpkg,
  layer = "clustering_c1_c2",
  quiet = TRUE
)


# ============================================================
# 5. GENERAL CONTROLS
# ============================================================

add_control(
  "general",
  "n_units",
  nrow(
    M0_sf
  )
)


if (!(
  "area_ha" %in%
  names(
    M0_sf
  )
)) {
  stop(
    "m0_ureh layer does not contain area_ha."
  )
}


add_control(
  "general",
  "total_area_ha",
  sum(
    M0_sf$area_ha,
    na.rm = TRUE
  )
)


# ============================================================
# 6. M0 CONTROLS
# ============================================================

required_M0_fields <- c(
  "UREH_predicha",
  "prob_UREH_predicha",
  "margen_clasificacion",
  "entropia_UREH"
)


missing_M0_fields <- setdiff(
  required_M0_fields,
  names(
    M0_sf
  )
)


if (
  length(
    missing_M0_fields
  ) > 0L
) {
  stop(
    "M0 spatial layer is missing fields: ",
    paste(
      missing_M0_fields,
      collapse = ", "
    )
  )
}


M0_counts <- table(
  M0_sf$UREH_predicha
)


get_M0_count <- function(
    state
) {
  
  if (!(
    state %in%
    names(
      M0_counts
    )
  )) {
    return(
      0
    )
  }
  
  
  as.numeric(
    M0_counts[
      state
    ]
  )
}


add_control(
  "M0",
  "n_aporte_conservada",
  get_M0_count(
    "aporte_conservada"
  )
)


add_control(
  "M0",
  "n_aporte_degradada",
  get_M0_count(
    "aporte_degradada"
  )
)


add_control(
  "M0",
  "n_transferencia_conservada",
  get_M0_count(
    "transferencia_conservada"
  )
)


add_control(
  "M0",
  "n_transferencia_degradada",
  get_M0_count(
    "transferencia_degradada"
  )
)


add_control(
  "M0",
  "n_receptora_conservada",
  get_M0_count(
    "receptora_conservada"
  )
)


add_control(
  "M0",
  "n_receptora_degradada",
  get_M0_count(
    "receptora_degradada"
  )
)


add_control(
  "M0",
  "dominant_probability_mean",
  mean(
    M0_sf$prob_UREH_predicha,
    na.rm = TRUE
  )
)


add_control(
  "M0",
  "classification_margin_median",
  median(
    M0_sf$margen_clasificacion,
    na.rm = TRUE
  )
)


add_control(
  "M0",
  "normalized_entropy_mean",
  mean(
    M0_sf$entropia_UREH,
    na.rm = TRUE
  )
)


# ============================================================
# 7. SENSITIVITY CONTROLS
# ============================================================

sensitivity <- read.csv(
  sensitivity_file,
  stringsAsFactors = FALSE,
  check.names = FALSE
)


required_sensitivity_fields <- c(
  "id",
  "escenario",
  "MAP_estable",
  "distancia_JS",
  "delta_entropia"
)


missing_sensitivity_fields <- setdiff(
  required_sensitivity_fields,
  names(
    sensitivity
  )
)


if (
  length(
    missing_sensitivity_fields
  ) > 0L
) {
  stop(
    "Sensitivity output is missing fields: ",
    paste(
      missing_sensitivity_fields,
      collapse = ", "
    )
  )
}


sensitivity$MAP_estable <- as_bool(
  sensitivity$MAP_estable
)


expected_scenarios <- c(
  "M1",
  "M2",
  "M3",
  "Sin cobertura",
  "Sin suelo + pendiente"
)


if (!setequal(
  unique(
    sensitivity$escenario
  ),
  expected_scenarios
)) {
  stop(
    "Unexpected sensitivity scenarios."
  )
}


extract_sensitivity <- function(
    scenario,
    prefix
) {
  
  x <- sensitivity[
    sensitivity$escenario ==
      scenario,
  ]
  
  
  if (
    nrow(
      x
    ) !=
    n_expected_units
  ) {
    stop(
      "Sensitivity scenario ",
      scenario,
      " does not contain ",
      n_expected_units,
      " units."
    )
  }
  
  
  add_control(
    "sensitivity",
    paste0(
      prefix,
      "_MAP_changes"
    ),
    sum(
      !x$MAP_estable
    )
  )
  
  
  add_control(
    "sensitivity",
    paste0(
      prefix,
      "_median_JS"
    ),
    median(
      x$distancia_JS,
      na.rm = TRUE
    )
  )
  
  
  add_control(
    "sensitivity",
    paste0(
      prefix,
      "_median_delta_H"
    ),
    median(
      x$delta_entropia,
      na.rm = TRUE
    )
  )
}


extract_sensitivity(
  "M1",
  "M1"
)


extract_sensitivity(
  "M2",
  "M2"
)


extract_sensitivity(
  "M3",
  "M3"
)


extract_sensitivity(
  "Sin cobertura",
  "diagnostic_no_cover"
)


extract_sensitivity(
  "Sin suelo + pendiente",
  "diagnostic_no_soil_slope"
)


# ============================================================
# 8. THORNTHWAITE-MATHER CONTROLS
# ============================================================

TM <- read.csv(
  TM_file,
  stringsAsFactors = FALSE,
  check.names = FALSE
)


required_TM_fields <- c(
  "id",
  "MAP_runoff_network",
  "MAP_runoff_TM",
  "JS_runoff",
  "delta_H_runoff",
  "MAP_UREH_network",
  "MAP_UREH_TM",
  "JS_UREH",
  "delta_H_UREH"
)


missing_TM_fields <- setdiff(
  required_TM_fields,
  names(
    TM
  )
)


if (
  length(
    missing_TM_fields
  ) > 0L
) {
  stop(
    "TM diagnostic is missing fields: ",
    paste(
      missing_TM_fields,
      collapse = ", "
    )
  )
}


if (
  nrow(
    TM
  ) !=
  n_expected_units
) {
  stop(
    "TM diagnostic must contain ",
    n_expected_units,
    " units."
  )
}


add_control(
  "TM",
  "runoff_MAP_changes",
  sum(
    TM$MAP_runoff_network !=
      TM$MAP_runoff_TM
  )
)


add_control(
  "TM",
  "UREH_MAP_changes",
  sum(
    TM$MAP_UREH_network !=
      TM$MAP_UREH_TM
  )
)


add_control(
  "TM",
  "runoff_median_JS",
  median(
    TM$JS_runoff,
    na.rm = TRUE
  )
)


add_control(
  "TM",
  "UREH_median_JS",
  median(
    TM$JS_UREH,
    na.rm = TRUE
  )
)


add_control(
  "TM",
  "runoff_median_delta_H",
  median(
    TM$delta_H_runoff,
    na.rm = TRUE
  )
)


add_control(
  "TM",
  "UREH_median_delta_H",
  median(
    TM$delta_H_UREH,
    na.rm = TRUE
  )
)


# ============================================================
# 9. CLUSTERING CONTROLS
# ============================================================

clustering <- read.csv(
  clustering_file,
  stringsAsFactors = FALSE,
  check.names = FALSE
)


required_clustering_fields <- c(
  "id",
  "cluster_C1",
  "cluster_C2",
  "silhouette_C1",
  "silhouette_C2"
)


missing_clustering_fields <- setdiff(
  required_clustering_fields,
  names(
    clustering
  )
)


if (
  length(
    missing_clustering_fields
  ) > 0L
) {
  stop(
    "Clustering assignments are missing fields: ",
    paste(
      missing_clustering_fields,
      collapse = ", "
    )
  )
}


if (
  nrow(
    clustering
  ) !=
  n_expected_units
) {
  stop(
    "Clustering assignments must contain ",
    n_expected_units,
    " units."
  )
}


if (
  anyDuplicated(
    clustering$id
  )
) {
  stop(
    "Duplicated ids in clustering assignments."
  )
}


k_C1 <- length(
  unique(
    clustering$cluster_C1
  )
)


k_C2 <- length(
  unique(
    clustering$cluster_C2
  )
)


cluster_stable <-
  clustering$cluster_C1 ==
  clustering$cluster_C2


n_stable <- sum(
  cluster_stable
)


n_reassigned <- sum(
  !cluster_stable
)


ARI_value <- adjusted_rand_index(
  clustering$cluster_C1,
  clustering$cluster_C2
)


add_control(
  "clustering",
  "k_C1",
  k_C1
)


add_control(
  "clustering",
  "k_C2",
  k_C2
)


add_control(
  "clustering",
  "silhouette_C1",
  mean(
    clustering$silhouette_C1,
    na.rm = TRUE
  )
)


add_control(
  "clustering",
  "silhouette_C2",
  mean(
    clustering$silhouette_C2,
    na.rm = TRUE
  )
)


add_control(
  "clustering",
  "ARI_C1_C2",
  ARI_value
)


add_control(
  "clustering",
  "n_reassigned",
  n_reassigned
)


add_control(
  "clustering",
  "n_stable",
  n_stable
)


# ============================================================
# 10. SPATIAL CONTROLS
# ============================================================

add_control(
  "spatial",
  "m0_features",
  nrow(
    M0_sf
  )
)


add_control(
  "spatial",
  "sensitivity_features",
  nrow(
    sensitivity_sf
  )
)


add_control(
  "spatial",
  "TM_features",
  nrow(
    TM_sf
  )
)


add_control(
  "spatial",
  "clustering_features",
  nrow(
    clustering_sf
  )
)


spatial_epsg <- sf::st_crs(
  M0_sf
)$epsg


if (
  is.na(
    spatial_epsg
  )
) {
  stop(
    "Generated M0 layer has no EPSG code."
  )
}


layer_epsgs <- c(
  
  sf::st_crs(
    M0_sf
  )$epsg,
  
  sf::st_crs(
    sensitivity_sf
  )$epsg,
  
  sf::st_crs(
    TM_sf
  )$epsg,
  
  sf::st_crs(
    clustering_sf
  )$epsg
)


if (
  anyNA(
    layer_epsgs
  ) ||
  length(
    unique(
      layer_epsgs
    )
  ) != 1L
) {
  stop(
    "Generated spatial layers do not share the same CRS."
  )
}


add_control(
  "spatial",
  "epsg",
  spatial_epsg
)


# ============================================================
# 11. COMBINE OBSERVED CONTROLS
# ============================================================

actual <- do.call(
  rbind,
  actual_rows
)


if (
  nrow(
    actual
  ) !=
  44L
) {
  stop(
    "Expected 44 observed controls; calculated ",
    nrow(
      actual
    ),
    "."
  )
}


if (
  anyDuplicated(
    actual[
      ,
      c(
        "block",
        "metric"
      )
    ]
  )
) {
  stop(
    "Duplicated observed controls."
  )
}


# ============================================================
# 12. MATCH EXPECTED AND OBSERVED RESULTS
# ============================================================

comparison <- merge(
  expected,
  actual,
  by = c(
    "block",
    "metric"
  ),
  all = TRUE,
  sort = FALSE
)


if (
  nrow(
    comparison
  ) !=
  44L
) {
  stop(
    "Expected and observed controls do not match one-to-one."
  )
}


if (
  anyNA(
    comparison$expected
  ) ||
  anyNA(
    comparison$actual
  )
) {
  stop(
    paste0(
      "At least one expected control has no observed counterpart, ",
      "or vice versa."
    )
  )
}


# Restore expected-results order

comparison$order_expected <- match(
  paste(
    comparison$block,
    comparison$metric,
    sep = "::"
  ),
  paste(
    expected$block,
    expected$metric,
    sep = "::"
  )
)


comparison <- comparison[
  order(
    comparison$order_expected
  ),
]


comparison$order_expected <- NULL


# ============================================================
# 13. CALCULATE DIFFERENCES AND PASS/FAIL
# ============================================================

comparison$absolute_difference <- abs(
  comparison$actual -
    comparison$expected
)


comparison$pass <-
  comparison$absolute_difference <=
  comparison$tolerance


comparison$status <- ifelse(
  comparison$pass,
  "PASS",
  "FAIL"
)


# ============================================================
# 14. WRITE CHECK REPORT
# ============================================================

report_file <- here::here(
  "checks",
  "reproducibility_report.csv"
)


write.csv(
  comparison[
    ,
    c(
      "block",
      "metric",
      "expected",
      "actual",
      "absolute_difference",
      "tolerance",
      "status"
    )
  ],
  report_file,
  row.names = FALSE,
  fileEncoding = "UTF-8"
)


# ============================================================
# 15. CONSOLE REPORT
# ============================================================

cat(
  "\n============================================\n"
)

cat(
  "REPRODUCIBILITY CHECK\n"
)

cat(
  "============================================\n\n"
)


display_table <- comparison[
  ,
  c(
    "block",
    "metric",
    "expected",
    "actual",
    "absolute_difference",
    "tolerance",
    "status"
  )
]


print(
  display_table,
  row.names = FALSE,
  digits = 10
)


n_pass <- sum(
  comparison$pass
)


n_fail <- sum(
  !comparison$pass
)


cat(
  "\n--------------------------------------------\n"
)

cat(
  "Controls passed: ",
  n_pass,
  " / ",
  nrow(
    comparison
  ),
  "\n",
  sep = ""
)


cat(
  "Controls failed: ",
  n_fail,
  "\n",
  sep = ""
)


cat(
  "Report: checks/reproducibility_report.csv\n"
)

cat(
  "--------------------------------------------\n"
)


# ============================================================
# 16. FINAL RESULT
# ============================================================

if (
  n_fail > 0L
) {
  
  failed_controls <- comparison[
    !comparison$pass,
    c(
      "block",
      "metric",
      "expected",
      "actual",
      "absolute_difference",
      "tolerance"
    )
  ]
  
  
  cat(
    "\nFAILED CONTROLS:\n\n"
  )
  
  
  print(
    failed_controls,
    row.names = FALSE,
    digits = 12
  )
  
  
  cat(
    "\n============================================\n\n"
  )
  
  
  stop(
    paste0(
      "Reproducibility check FAILED: ",
      n_fail,
      " of ",
      nrow(
        comparison
      ),
      " controls differ from the verified baseline."
    )
  )
}


cat(
  "\nAll verified analytical and spatial controls match ",
  "the reference baseline.\n",
  sep = ""
)


cat(
  "These checks confirm computational reproducibility of the ",
  "specified outputs; they do not constitute external model validation.\n"
)


cat(
  "============================================\n\n"
)


message(
  "check_reproducibility.R completed successfully."
)

message(
  "44 / 44 controls passed."
)